<a href="https://colab.research.google.com/github/PWaweru88/PWaweru88-Projects/blob/master/Spam_Detection_Program.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import nltk
from nltk.corpus import stopwords
import string

In [ ]:
# 1 = spam
# 0 = not spam

In [ ]:
#load data
from google.colab import files
uploaded = files.upload()

Saving emails.csv to emails.csv


In [ ]:

df= pd.read_csv('emails.csv')
df.head()

text  spam
0  Subject: naturally irresistible your corporate...     1
1  Subject: the stock trading gunslinger  fanny i...     1
2  Subject: unbelievable new homes made easy  im ...     1
3  Subject: 4 color printing special  request add...     1
4  Subject: do not have money , get software cds ...     1

In [ ]:
df.shape

(5728, 2)

In [ ]:
df.dtypes

text    object
spam     int64
dtype: object

In [ ]:
#check for and delete duplicates
df.drop_duplicates(inplace=True)

In [ ]:
#new shape
df.shape

(5695, 2)

In [ ]:
#check for missing values for each column
df.isnull().sum()

text    0
spam    0
dtype: int64

In [ ]:
#download stopwords package
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
#function to process all the texts
def process_text(text):
  #1. Remove punctuation
  #2. Remove stopwords(i.e useless words)
  #3. Return list of clean text words

  #1
  nopunc = [char for char in text if char not in string.punctuation]
  nopunc = ''.join(nopunc)

  #2
  clean_words = [word for word in nopunc.split() if word.lower not in stopwords.words('english')]

  #3
  return clean_words

In [ ]:
#show tokenization (a list of tokens, also known as lemmas)
df['text'].head().apply(process_text)


0    [Subject, naturally, irresistible, your, corpo...
1    [Subject, the, stock, trading, gunslinger, fan...
2    [Subject, unbelievable, new, homes, made, easy...
3    [Subject, 4, color, printing, special, request...
4    [Subject, do, not, have, money, get, software,...
Name: text, dtype: object

In [ ]:
# convert collection of text into a matrix of tokens
from sklearn.feature_extraction.text import CountVectorizer

#bow= 'bag of words'
messages_bow = CountVectorizer(analyzer = process_text).fit_transform(df['text'])

In [ ]:
#split data into 80% train, 20% test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(messages_bow, df['spam'], test_size = 0.2, random_state = 0)

In [ ]:
messages_bow.shape

(5695, 37380)

In [ ]:
#create and train the Naive Bayes Classifier
from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB().fit(X_train,y_train)

In [ ]:
#print prediction
print(classifier.predict(X_train))

#print actual values
print(y_train.values)


[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]


In [ ]:
#evaluate model on the training dataset
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
pred = classifier.predict(X_train)
print(classification_report(y_train, pred))
print()
print('Confusion Matrix: \n', confusion_matrix(y_train, pred))
print()
print('Accuracy: ' ,accuracy_score(y_train,pred))

              precision    recall  f1-score   support

           0       1.00      0.99      1.00      3457
           1       0.98      1.00      0.99      1099

    accuracy                           1.00      4556
   macro avg       0.99      1.00      0.99      4556
weighted avg       1.00      1.00      1.00      4556


Confusion Matrix: 
 [[3439   18]
 [   1 1098]]

Accuracy:  0.9958296751536435


In [ ]:
#print prediction
print(classifier.predict(X_test))

#print actual values
print(y_test.values)

[1 0 0 ... 0 0 0]
[1 0 0 ... 0 0 0]


In [ ]:
#evaluate model on the training dataset
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
pred = classifier.predict(X_test)
print(classification_report(y_test, pred))
print()
print('Confusion Matrix: \n', confusion_matrix(y_test, pred))
print()
print('Accuracy: ' ,accuracy_score(y_test,pred))

              precision    recall  f1-score   support

           0       1.00      0.99      0.99       870
           1       0.97      0.99      0.98       269

    accuracy                           0.99      1139
   macro avg       0.99      0.99      0.99      1139
weighted avg       0.99      0.99      0.99      1139


Confusion Matrix: 
 [[863   7]
 [  2 267]]

Accuracy:  0.9920983318700615
